name: CI

on:
  push:
    branches: ['*']  # Trigger on push events for all branches
    tags-ignore: ['*']  # Ignore push events on all tags
  pull_request:
    branches: ['master']  # Trigger on pull requests to master
  workflow_dispatch:  # Allow manual triggering of workflow

jobs:
  build:
    uses: ./.github/workflows/cmake.yml
    with:
      build_type: ${{ (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') && '"Debug","Release"' || '"Debug"' }}
      upload_artifacts: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' }}